/**
 * OpenAPI 3.1 document for /api/v1. Hand-maintained (kept small on purpose);
 * every route's Zod schema is the source of truth for validation.
 */
export function buildOpenApi(baseUrl: string) {
  const envelope = (data: unknown) => ({ type: "object", properties: { ok: { type: "boolean", const: true }, data, meta: { type: "object", additionalProperties: true } } });
  const error = { type: "object", properties: { ok: { type: "boolean", const: false }, error: { type: "object", properties: { code: { type: "string" }, message: { type: "string" }, details: {} } } } };
  const productCard = { $ref: "#/components/schemas/ProductCard" };
  const list = (item: unknown) => ({ type: "array", items: item });
  const q = (name: string, description: string, schema: unknown = { type: "string" }, required = false) => ({ name, in: "query", description, schema, required });
  const pathParam = (name: string) => ({ name, in: "path", required: true, schema: { type: "string" } });
  const ok = (data: unknown, description = "OK") => ({ 200: { description, content: { "application/json": { schema: envelope(data) } } }, 400: { description: "Validation error", content: { "application/json": { schema: error } } } });
  const listQuery = [
    q("q", "Full-text search"), q("category", "Category slug"), q("collection", "Curated collection slug"),
    q("fabric", "Comma-separated"), q("weave", "Comma-separated"), q("craft", "Comma-separated"), q("occasion", "Comma-separated"), q("color", "Comma-separated"), q("motif", "Comma-separated"), q("border", "Comma-separated"),
    q("priceMin", "", { type: "number" }), q("priceMax", "", { type: "number" }), q("discountMin", "Minimum discount %", { type: "number" }), q("inStock", "", { type: "boolean" }), q("newArrivals", "", { type: "boolean" }),
    q("sort", "", { type: "string", enum: ["featured", "price_asc", "price_desc", "newest", "best_selling"] }), q("page", "", { type: "integer", default: 1 }), q("limit", "", { type: "integer", default: 24, maximum: 96 }),
  ];

  return {
    openapi: "3.1.0",
    info: { title: "Woven Essence API", version: "1.0.0", description: "REST API for the Woven Essence storefront and admin. Master data (products, categories, stores) is read from RetailERP; website-owned data lives in a separate DB. All responses use `{ ok, data, meta }` / `{ ok:false, error }` envelopes." },
    servers: [{ url: `${baseUrl}/api/v1` }],
    tags: [{ name: "Catalogue" }, { name: "Cart" }, { name: "Checkout" }, { name: "Auth" }, { name: "Account" }, { name: "Content" }, { name: "Admin" }, { name: "System" }],
    components: {
      securitySchemes: { customerCookie: { type: "apiKey", in: "cookie", name: "we_session" }, adminCookie: { type: "apiKey", in: "cookie", name: "we_admin" } },
      schemas: {
        ProductCard: { type: "object", properties: { id: { type: "string" }, sku: { type: "string" }, slug: { type: "string" }, name: { type: "string" }, category: { type: "string" }, fabric: { type: "string" }, color: { type: "string" }, pricing: { $ref: "#/components/schemas/Pricing" }, stock: { $ref: "#/components/schemas/Stock" }, images: list({ type: "string" }), isNewArrival: { type: "boolean" } } },
        Pricing: { type: "object", properties: { mrp: { type: "number" }, sellingPrice: { type: "number" }, discountPercent: { type: "number" }, gstPercent: { type: "number" }, currency: { type: "string", const: "INR" } } },
        Stock: { type: "object", properties: { qty: { type: "integer" }, status: { type: "string", enum: ["in_stock", "low_stock", "out_of_stock"] } } },
        Product: { allOf: [productCard, { type: "object", properties: { description: { type: "string" }, subCategory: { type: "string" }, weave: { type: "string" }, craft: { type: "string" }, occasion: list({ type: "string" }), motif: { type: "string" }, border: { type: "string" }, blouseIncluded: { type: "boolean" }, careInstructions: { type: "string" }, dimensions: { type: "object" }, tags: list({ type: "string" }), source: { type: "string", enum: ["mock", "erp"] } } }] },
        Facets: { type: "object", properties: { groups: list({ type: "object", properties: { key: { type: "string" }, label: { type: "string" }, options: list({ type: "object", properties: { value: { type: "string" }, label: { type: "string" }, count: { type: "integer" } } }) } }), price: { type: "object", properties: { min: { type: "number" }, max: { type: "number" } } }, availability: { type: "object" }, discount: list({ type: "object" }) } },
        Address: { type: "object", required: ["name", "phone", "line1", "city", "state", "pincode"], properties: { name: { type: "string" }, phone: { type: "string", pattern: "^[6-9]\\d{9}$" }, line1: { type: "string" }, line2: { type: "string" }, city: { type: "string" }, state: { type: "string" }, pincode: { type: "string", pattern: "^[1-9][0-9]{5}$" }, country: { type: "string", default: "India" }, isDefault: { type: "boolean" } } },
        CartView: { type: "object", properties: { lines: list({ type: "object", properties: { sku: { type: "string" }, qty: { type: "integer" }, product: productCard } }), unavailable: list({ type: "object" }), couponCode: { type: "string" }, totals: { type: "object", properties: { itemCount: { type: "integer" }, subTotal: { type: "number" }, productDiscount: { type: "number" }, couponDiscount: { type: "number" }, shippingCharge: { type: "number" }, gstTotal: { type: "number" }, netAmount: { type: "number" }, freeShippingGap: { type: "number" }, couponError: { type: "string" } } } } },
        Order: { type: "object", properties: { id: { type: "string" }, orderNo: { type: "string" }, items: list({ type: "object" }), subTotal: { type: "number" }, discountTotal: { type: "number" }, gstTotal: { type: "number" }, shippingCharge: { type: "number" }, netAmount: { type: "number" }, paymentMode: { type: "string" }, paymentStatus: { type: "string" }, orderStatus: { type: "string", enum: ["Placed", "Confirmed", "Packed", "Shipped", "Delivered", "Cancelled", "Returned"] }, shippingAddress: { $ref: "#/components/schemas/Address" }, awbNo: { type: "string" }, couponCode: { type: "string" }, createdAt: { type: "string", format: "date-time" } } },
        Error: error,
      },
    },
    paths: {
      "/health": { get: { tags: ["System"], summary: "Liveness + DB status", responses: ok({ type: "object" }) } },
      "/erp/status": { get: { tags: ["System"], summary: "Which data source is active and whether it responds", responses: ok({ type: "object" }) } },
      "/products": { get: { tags: ["Catalogue"], summary: "List / search products", parameters: listQuery, responses: ok(list(productCard)) } },
      "/products/facets": { get: { tags: ["Catalogue"], summary: "Facet counts for the same filters", parameters: listQuery, responses: ok({ $ref: "#/components/schemas/Facets" }) } },
      "/products/{slug}": { get: { tags: ["Catalogue"], summary: "Product detail (+related)", parameters: [pathParam("slug")], responses: { ...ok({ $ref: "#/components/schemas/Product" }), 404: { description: "Not found" } } } },
      "/categories": { get: { tags: ["Catalogue"], summary: "Category tree", responses: ok({ type: "array" }) } },
      "/stores": { get: { tags: ["Catalogue"], summary: "Physical stores", responses: ok({ type: "array" }) } },
      "/pincode": { get: { tags: ["Checkout"], summary: "Serviceability + ETA", parameters: [q("pin", "6-digit pincode", { type: "string" }, true)], responses: ok({ type: "object" }) } },
      "/cart": {
        get: { tags: ["Cart"], summary: "Current cart (cookie-scoped)", responses: ok({ $ref: "#/components/schemas/CartView" }) },
        post: { tags: ["Cart"], summary: "Add line", requestBody: { content: { "application/json": { schema: { type: "object", required: ["sku"], properties: { sku: { type: "string" }, qty: { type: "integer", default: 1 } } } } } }, responses: ok({ $ref: "#/components/schemas/CartView" }) },
        patch: { tags: ["Cart"], summary: "Set qty (0 removes)", requestBody: { content: { "application/json": { schema: { type: "object", required: ["sku", "qty"], properties: { sku: { type: "string" }, qty: { type: "integer" } } } } } }, responses: ok({ $ref: "#/components/schemas/CartView" }) },
        delete: { tags: ["Cart"], summary: "Clear cart", responses: ok({ $ref: "#/components/schemas/CartView" }) },
      },
      "/cart/coupon": { post: { tags: ["Cart"], summary: "Apply / remove coupon", requestBody: { content: { "application/json": { schema: { type: "object", properties: { code: { type: ["string", "null"] } } } } } }, responses: ok({ $ref: "#/components/schemas/CartView" }) } },
      "/wishlist": { get: { tags: ["Cart"], summary: "Wishlist SKUs", responses: ok(list({ type: "string" })) }, post: { tags: ["Cart"], summary: "Toggle SKU", requestBody: { content: { "application/json": { schema: { type: "object", required: ["sku"], properties: { sku: { type: "string" } } } } } }, responses: ok(list({ type: "string" })) } },
      "/checkout": { post: { tags: ["Checkout"], summary: "Place order (COD) or start/confirm Razorpay payment", requestBody: { content: { "application/json": { schema: { type: "object", required: ["address", "paymentMode"], properties: { address: { $ref: "#/components/schemas/Address" }, paymentMode: { type: "string", enum: ["COD", "RAZORPAY"] }, email: { type: "string" }, saveAddress: { type: "boolean" }, payment: { type: "object", properties: { orderId: { type: "string" }, paymentId: { type: "string" }, signature: { type: "string" } } } } } } } }, responses: ok({ type: "object", properties: { step: { type: "string", enum: ["payment", "done"] }, orderNo: { type: "string" }, gateway: { type: "object" } } }) } },
      "/orders/{orderNo}": { get: { tags: ["Checkout"], summary: "Order lookup (owner or matching phone)", parameters: [pathParam("orderNo"), q("phone", "Phone used on the order")], responses: ok({ $ref: "#/components/schemas/Order" }) } },
      "/auth/register": { post: { tags: ["Auth"], summary: "Create a customer account → sets we_session cookie, merges guest cart", requestBody: { content: { "application/json": { schema: { type: "object", required: ["name", "email", "password"], properties: { name: { type: "string" }, email: { type: "string" }, phone: { type: "string", description: "Optional 10-digit Indian mobile" }, password: { type: "string", minLength: 8 } } } } } }, responses: ok({ type: "object" }) } },
      "/auth/login": { post: { tags: ["Auth"], summary: "Email + password login → sets we_session cookie, merges guest cart (locks for 15 min after 5 failures)", requestBody: { content: { "application/json": { schema: { type: "object", required: ["email", "password"], properties: { email: { type: "string" }, password: { type: "string" } } } } } }, responses: ok({ type: "object" }) } },
      "/auth/otp/send": { post: { tags: ["Auth"], summary: "Send OTP (dev: returned as devOtp)", requestBody: { content: { "application/json": { schema: { type: "object", required: ["mobile"], properties: { mobile: { type: "string" } } } } } }, responses: ok({ type: "object" }) } },
      "/auth/otp/verify": { post: { tags: ["Auth"], summary: "Verify OTP → sets we_session cookie, merges guest cart", requestBody: { content: { "application/json": { schema: { type: "object", required: ["mobile", "code"], properties: { mobile: { type: "string" }, code: { type: "string" }, name: { type: "string" } } } } } }, responses: ok({ type: "object" }) } },
      "/auth/logout": { post: { tags: ["Auth"], summary: "Clear customer session", responses: ok({ type: "object" }) } },
      "/auth/me": { get: { tags: ["Auth"], summary: "Current customer (null if guest)", security: [{ customerCookie: [] }], responses: ok({ type: ["object", "null"] }) }, patch: { tags: ["Auth"], summary: "Update profile", security: [{ customerCookie: [] }], responses: ok({ type: "object" }) } },
      "/account/orders": { get: { tags: ["Account"], summary: "My orders", security: [{ customerCookie: [] }], parameters: [q("page", "", { type: "integer" })], responses: ok(list({ $ref: "#/components/schemas/Order" })) } },
      "/account/addresses": { put: { tags: ["Account"], summary: "Replace address book", security: [{ customerCookie: [] }], requestBody: { content: { "application/json": { schema: { type: "object", properties: { addresses: list({ $ref: "#/components/schemas/Address" }) } } } } }, responses: ok({ type: "object" }) } },
      "/reviews": { get: { tags: ["Content"], summary: "Approved reviews for a SKU", parameters: [q("sku", "", { type: "string" }, true)], responses: ok({ type: "object" }) }, post: { tags: ["Content"], summary: "Submit review (moderated)", requestBody: { content: { "application/json": { schema: { type: "object", required: ["sku", "customerName", "rating", "body"], properties: { sku: { type: "string" }, customerName: { type: "string" }, rating: { type: "integer", minimum: 1, maximum: 5 }, title: { type: "string" }, body: { type: "string" } } } } } }, responses: ok({ type: "object" }) } },
      "/enquiries": { post: { tags: ["Content"], summary: "Contact / support / newsletter / product enquiry", requestBody: { content: { "application/json": { schema: { type: "object", properties: { type: { type: "string", enum: ["contact", "support", "product", "whatsapp", "newsletter"] }, name: { type: "string" }, mobile: { type: "string" }, email: { type: "string" }, message: { type: "string" }, sku: { type: "string" } } } } } }, responses: ok({ type: "object" }) } },
      "/admin/auth/login": { post: { tags: ["Admin"], summary: "Admin login → we_admin cookie", requestBody: { content: { "application/json": { schema: { type: "object", required: ["email", "password"], properties: { email: { type: "string" }, password: { type: "string" } } } } } }, responses: ok({ type: "object" }) } },
      "/admin/dashboard": { get: { tags: ["Admin"], summary: "KPIs", security: [{ adminCookie: [] }], responses: ok({ type: "object" }) } },
      "/admin/assistant": { get: { tags: ["Admin"], summary: "AI assistant status: what it can look up for this admin", security: [{ adminCookie: [] }], responses: ok({ type: "object" }) }, post: { tags: ["Admin"], summary: "Ask the AI assistant; streams newline-delimited JSON events (activity, text, error, done)", security: [{ adminCookie: [] }], responses: { 200: { description: "application/x-ndjson event stream" } } } },
      "/admin/products": { get: { tags: ["Admin"], summary: "RetailERP barcodeLabel records + web meta (read-only master data)", security: [{ adminCookie: [] }], parameters: [q("q", "Barcode, item code, old barcode, item name or description"), q("status", "Exact ERP status, e.g. IN_STOCK"), q("group", "productgroup id"), q("business", "business id"), q("uomType", "PC or MTR"), q("page", "", { type: "integer", default: 1 }), q("limit", "", { type: "integer", default: 40, maximum: 96 })], responses: { ...ok({ type: "array" }), 503: { description: "RetailERP unreachable", content: { "application/json": { schema: error } } } } }, patch: { tags: ["Admin"], summary: "Update website overlay (slug/SEO/featured); sku = barcode", security: [{ adminCookie: [] }], responses: ok({ type: "object" }) } },
      "/admin/products/facets": { get: { tags: ["Admin"], summary: "Filter options with live counts (status, group, business, UOM)", security: [{ adminCookie: [] }], responses: ok({ type: "object" }) } },
      "/admin/orders": { get: { tags: ["Admin"], summary: "List orders", security: [{ adminCookie: [] }], parameters: [q("status", ""), q("q", ""), q("from", "", { type: "string", format: "date" }), q("to", "", { type: "string", format: "date" }), q("page", "", { type: "integer" })], responses: ok(list({ $ref: "#/components/schemas/Order" })) } },
      "/admin/orders/{orderNo}": { get: { tags: ["Admin"], summary: "Order + customer + allowed transitions", security: [{ adminCookie: [] }], parameters: [pathParam("orderNo")], responses: ok({ type: "object" }) }, patch: { tags: ["Admin"], summary: "Change status / AWB / note (workflow enforced)", security: [{ adminCookie: [] }], parameters: [pathParam("orderNo")], requestBody: { content: { "application/json": { schema: { type: "object", properties: { status: { type: "string" }, note: { type: "string" }, awbNo: { type: "string" } } } } } }, responses: ok({ $ref: "#/components/schemas/Order" }) } },
      "/admin/customers": { get: { tags: ["Admin"], summary: "List customers", security: [{ adminCookie: [] }], responses: ok({ type: "array" }) } },
      "/admin/inventory": { get: { tags: ["Admin"], summary: "Stock summary + low/out-of-stock", security: [{ adminCookie: [] }], responses: ok({ type: "object" }) } },
      "/admin/reports": { get: { tags: ["Admin"], summary: "Sales reports", security: [{ adminCookie: [] }], parameters: [q("from", ""), q("to", "")], responses: ok({ type: "object" }) } },
      "/admin/settings": { get: { tags: ["Admin"], summary: "Site settings", security: [{ adminCookie: [] }], responses: ok({ type: "object" }) }, patch: { tags: ["Admin"], summary: "Deep-merge site settings", security: [{ adminCookie: [] }], responses: ok({ type: "object" }) } },
      "/admin/erp/test": { post: { tags: ["Admin"], summary: "Test master-data connection", security: [{ adminCookie: [] }], responses: ok({ type: "object" }) } },
      "/admin/erp/sync-meta": { post: { tags: ["Admin"], summary: "Create slugs/SEO rows for new SKUs", security: [{ adminCookie: [] }], responses: ok({ type: "object" }) } },
      "/admin/audit": { get: { tags: ["Admin"], summary: "Audit log", security: [{ adminCookie: [] }], responses: ok({ type: "array" }) } },
      "/admin/{resource}": {
        get: { tags: ["Admin"], summary: "Generic list — resource ∈ menu | banners | collections | pages | testimonials | homepage | coupons | reviews | enquiries | roles | users | productMeta", security: [{ adminCookie: [] }], parameters: [pathParam("resource"), q("q", ""), q("page", "", { type: "integer" }), q("limit", "", { type: "integer" }), q("sort", "field:1|-1"), q("filter[field]", "Equality filter")], responses: ok({ type: "array" }) },
        post: { tags: ["Admin"], summary: "Generic create", security: [{ adminCookie: [] }], parameters: [pathParam("resource")], responses: ok({ type: "object" }) },
      },
      "/admin/{resource}/{id}": {
        get: { tags: ["Admin"], summary: "Generic read", security: [{ adminCookie: [] }], parameters: [pathParam("resource"), pathParam("id")], responses: ok({ type: "object" }) },
        patch: { tags: ["Admin"], summary: "Generic update", security: [{ adminCookie: [] }], parameters: [pathParam("resource"), pathParam("id")], responses: ok({ type: "object" }) },
        delete: { tags: ["Admin"], summary: "Generic delete", security: [{ adminCookie: [] }], parameters: [pathParam("resource"), pathParam("id")], responses: ok({ type: "object" }) },
      },
    },
  };
}
