/**
 * Local catalogue imagery in public/images, generated by scripts/make-site-images.py.
 * Used by the seed and by `npm run images` (which re-points an existing database).
 */
const SHOTS = ["saree-pink", "saree-trio", "saree-magenta", "saree-blue", "saree-purple", "saree-red", "saree-coral", "saree-portrait", "saree-wine", "saree-group"];
const FABRIC = ["fabric-pallu", "fabric-jaal", "fabric-pleats", "fabric-paithani"];
const PLAIN = ["plain-coral", "plain-magenta"];
const DUPATTA = ["dupatta-drape", "dupatta-gold"];
const FAMILIES = ["red", "gold", "green", "blue", "teal", "purple", "pink", "ivory", "black"];
const COLOR_FAMILY: Record<string, string> = {
  Maroon: "red", Red: "red", Orange: "gold", Mustard: "gold", Gold: "gold", Beige: "ivory", Ivory: "ivory", Black: "black",
  "Emerald Green": "green", "Bottle Green": "green", "Royal Blue": "blue", "Peacock Blue": "blue", Teal: "teal",
  Lavender: "purple", Purple: "purple", Pink: "pink",
};

const src = (name: string) => `/images/${name}.jpg`;
const at = <T>(arr: readonly T[], n: number) => arr[n % arr.length];
const hash = (s: string) => Array.from(s).reduce((h, c) => (h * 31 + c.charCodeAt(0)) >>> 0, 7);
const swatch = (bases: string[], family: string, n: number) => src(`${at(bases, n)}-${family}`);

/** SKUs look like WE-SAR-0001; the code picks the pool, the number rotates through it. */
export function productImages(sku: string, color?: string): string[] {
  const n = Number(sku.replace(/\D/g, "")) || hash(sku);
  const family = (color && COLOR_FAMILY[color]) || at(FAMILIES, n);
  switch (sku.split("-")[1]) {
    case "FAB": return [swatch(FABRIC, family, n), swatch(FABRIC, family, n + 1), swatch(FABRIC, family, n + 2)];
    case "PLF": return [swatch(PLAIN, family, n), swatch(PLAIN, family, n + 1)];
    case "DUP": return [swatch(DUPATTA, family, n), swatch(DUPATTA, family, n + 1), swatch(FABRIC, family, n)];
    default: return [src(at(SHOTS, n)), swatch(FABRIC, family, n), src(at(SHOTS, n + 3))];
  }
}

const TOP_CATEGORY: Record<string, string> = {
  Sarees: src("saree-trio"),
  Fabrics: src("fabric-pallu"),
  "Plain Fabrics": src("plain-coral"),
  Dupatta: src("dupatta-drape"),
};

export function categoryImage(name: string, parentName?: string | null): string {
  if (!parentName) return TOP_CATEGORY[name] ?? src(at(SHOTS, hash(name)));
  const n = hash(name);
  const family = at(FAMILIES, n);
  if (parentName === "Fabrics") return swatch(FABRIC, family, n);
  if (parentName === "Plain Fabrics") return swatch(PLAIN, family, n);
  if (parentName === "Dupatta") return swatch(DUPATTA, family, n);
  return src(at(SHOTS, n));
}

/** Indexed by banner sortOrder. */
export const HERO_IMAGES = [1, 2, 3].map((i) => ({ desktop: src(`hero-${i}`), mobile: src(`hero-${i}-m`) }));
export const LIFESTYLE_IMAGES = [src("life-1"), src("life-2")];

export const COLLECTION_BANNERS: Record<string, string> = {
  "yanai-motif-sarees": src("col-yanai"),
  "bridal-kanchipuram": src("col-bridal"),
  "festive-banarasi": src("col-banarasi"),
  "under-5000": src("col-5000"),
  "editors-picks": src("col-editors"),
};
